### ISSUE TITLE
Crash while trying to open a directory

### ISSUE THREAD

**Issue by LoZack19** [FrancescoLFM/c-fat-lib#2]
Structure of the FAT filesystem:
![image](https://user-images.githubusercontent.com/71092108/216401831-f88bd1ec-4553-475c-9e54-6d7354929348.png)

Call to the program:
`$ valgrind ./fatinfo /dir`

Output of valgrind:
![image](https://user-images.githubusercontent.com/71092108/216402247-a3187908-c921-4034-b164-01cbaa097af8.png)

Point of crash (gdb output):
![image](https://user-images.githubusercontent.com/71092108/216402475-c6eba7ab-aeff-4ba2-bfe4-f197647a2716.png)

**Comment by LoZack19** [comment]
![image](https://user-images.githubusercontent.com/71092108/216402937-0c3807ed-dc19-4ef4-8498-d81e3dc67103.png)
The problem seems to be linked to the fact that `s1` is `NULL`. The `token` passed by the `fat_file_open_recursive` is NULL in the first recursive call. The failiure will most probably be in the strtok_path.

**Comment by FrancescoLFM** [comment]
Thanks for testing my code, I solved this by checking if the token is null after the call to strtok_path.
char *token = strtok_path(NULL, &is_dir);
```
if (token == NULL)
    return NULL;
```

https://user-images.githubusercontent.com/60569057/216456976-2c7ebde8-cdd5-406b-968d-922d0def9171.mp4
